### PR TITLE
feat: add stylecss file to the HTML and add color to the add and deleteAll button 

### PR DESCRIPTION
**Pull request by LuminousBlade**
I added style.css file in the HTML and improved the file's identation.
In the style.css file, I have made the add and deleteAll buttons more vibrant.

### CODE REVIEW

**Comment by SkySilkK** [comment]
Could you please also improve the colors of todo heading it looks kinda dull. Thanks for your contributions 😊. I will merge after that..

**Comment by LuminousBlade** [comment]
Can you specify the exact color you are looking for the todo heading?

**Comment by SkySilkK** [comment]
Ummm pink maybe will that do?

**Comment by LuminousBlade** [comment]
yeah sure lemme try!

**Comment by LuminousBlade** [comment]
I have added pink color to the heading. Do view it and let me know if that suits you!

**Comment by SkySilkK** [comment]
Excellent! I will merge it now! **Thanks again!**

**Pull request merged**
